apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend
spec:
  selector:
    app: yolo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # to expose the front end to the internet